let works = [
  {
    title: 'Cake Shop',
    pic: 'img/cake-shop.png',
    description: 'FullStack App with Nodejs, MongoDB and React.js',
    href: 'https://cake-shop-app-kirsi.netlify.app/',
    buttonText: 'Go to App!',
  },
  {
    title: 'Daily Dose of Dopamine',
    pic: 'img/vision-board.png',
    description: 'FullStack App with Node.js, React.js and MongoDB',
    href: 'https://daily-dose-of-dopamine.herokuapp.com/',
    buttonText: 'Go to App!',
  },
  {
    title: 'Learn Words',
    pic: 'img/learn-words.png',
    description: 'React.js App with Redux',
    href: 'https://learn-words-now.herokuapp.com/',
    buttonText: 'Go to App!',
  },
  {
    title: 'Notes Game',
    pic: 'img/game.png',
    description: 'JavaScript App with Material Kit',
    href: 'https://notes-game.now.sh/',
    buttonText: 'Go to App!',
  },
  // {
  //   title: "Countries of the World",
  //   pic: "img/country-app.png",
  //   description: "React.js App with Redux",
  //   href: "https://kt-country-app.netlify.app/",
  //   buttonText: "Go to App!",
  // },
  {
    title: 'Expensify',
    pic: 'img/expensify.png',
    description: 'React.js App with Redux',
    href: 'https://kirsi-expensify-app.herokuapp.com/',
    buttonText: 'Go to App!',
  },
  {
    title: 'Indecision App',
    pic: 'img/indecision-app.png',
    description: 'React.js App',
    href: 'https://decisions-decisions.herokuapp.com/',
    buttonText: 'Go to App!',
  },
  // {
  //   title: "Star Wars",
  //   pic: "img/starwars.png",
  //   description:
  //     "React.js App with Typescript, Redux and Redux-saga",
  //   href: "https://star-wars-app-kirsi.netlify.app/",
  //   buttonText: "Go to App!",
  // },
  // {
  //   title: "Berlin Bike",
  //   pic: "img/bike.png",
  //   description: "E-Commerce Web App with Ruby on Rails",
  //   href: "https://bike-store-berlin.herokuapp.com/",
  //   buttonText: "Go to App!",
  // },
]
